### ISSUE TITLE
log's clone op can fail if you're storing a function on your state

### ISSUE THREAD

**Issue by toddself** [choojs/choo-devtools#15]
the call to clone fails when you store a bound function on the state object.

deep clone is also a super expensive operation -- would love to figure out how we can do without a recursive deep-clone.

![](https://usercontent.irccloud-cdn.com/file/jv287mQP/Screen%20Shot%202017-10-23%20at%2017.18.07.png)

**Comment by yoshuawuyts** [comment]
@toddself one of the things `choo.debug` does is enable state snapshots, which is useful when you find yourself in a pickle, and are trying to figure out what changed between events. In addition to that we also log out the locations in code where the respective edits happened.

Because deep cloning is expensive, we warn people they've got `choo.debug` enabled every time they load their page — it should only be used while debugging specific bits. Perhaps our language could be a bit, err, firmer?

Agree this shouldn't the throwing tho. I think if we detect a bound function inside the state, we should catch the `Error`, and simply warn that we cannot take a state snapshot. I think ignoring bound functions might make things more confusing.

Hope this makes sense — PRs to improve the lot welcome! :sparkles:

**Comment by yoshuawuyts** [comment]
@toddself does this answer your question?

**Comment by yoshuawuyts** [comment]
ping @toddself

**Comment by YerkoPalma** [comment]
Would a simple try/catch when clone is called and a nice message fix this issue?

**Comment by yoshuawuyts** [comment]
@YerkoPalma yeah, that would probably be a good solution!
